name: hola mundo
on:
  push:
    branches: master
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: hola mundo
      run: |
        echo Hello, world!
        lsb_release -a
        echo ===========
        env
